kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: playground
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30001
    hostPort: 30001
    listenAddress: "0.0.0.0"
    protocol: tcp
  extraMounts:
  - hostPath: /home/jimc/data
    containerPath: /data
- role: worker
- role: worker
- role: worker

